version: "2.4"
services:

  # Mysql Instance
  mysql-db:
    image: mysql:5.7 
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_DATABASE=db
      ## Example passwords DONT USE
      - MYSQL_USER=some-be-service
      - MYSQL_PASSWORD=p@ssw0rd
      # Password for root access
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    # The mysql default image only supports one db in the MYSQL_DATABASE var, so below is to create a second database on startup
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS db; CREATE DATABASE IF NOT EXISTS test_db;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    ports:
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
    volumes:
      - datavolume:/var/lib/mysql

  # Migration to get database set up
  migration:
    image: boxfuse/flyway:latest
    restart: on-failure
    command: -url=jdbc:mysql://mysql-db:3306/db?verifyServerCertificate=false&useSSL=true -schemas=db -user=root -password=root migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on: 
      mysql-db:
        condition: service_healthy

  # Migration to get database set up for a test db using the same migrations
  migration-test-db:
    image: boxfuse/flyway:latest
    restart: on-failure
    command: -url=jdbc:mysql://mysql-db:3306/test_db?verifyServerCertificate=false&useSSL=true -schemas=test_db -user=root -password=root migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on: 
      mysql-db:
        condition: service_healthy


volumes:
  datavolume: